### ISSUE TITLE
Content Fragment component

### ISSUE THREAD

**Issue by stein-rockware** [adobe/aem-core-email-components#10]
Allows embedding a Content Fragment in structured or text format.

Requirements:
* Capability to use the Campaign personalization fields in the RTE of the CF Editor.
* Option to embed the CF as single element.
* Disallow the possibility to insert in-between content.
* Avoid further wrapping DIV to be added to the output.

- [x] Implement CF based on core CF component
- [x] Integrate CF Editor plugin for personalization
- [x] Disallow the possibility to insert in-between content.
- [x] Remove wrapping DIVs
- [x] Make sure RTE personalization is working
- [x] Write Selenium test
- [x] Document

Estimation: M (10 Days)

**Comment by VjekoSulentic** [comment]
Relevant PRs merged in CQ/mcm and CQ/dam-contentfragment projects.
