### ISSUE TITLE
Increase code coverage of unit tests > 80%

### ISSUE THREAD

**Issue by bpauli** [adobe/aem-core-email-components#107]
According to Codecov (https://app.codecov.io/gh/adobe/aem-core-email-components) the line code coverage by unit tests is currently  around 53%. To be align with the core component project the email component project should also include the `jacoco-maven-plugin` in the build with a minimum coverage of 80% [1]

[1] https://github.com/adobe/aem-core-wcm-components/blob/main/bundles/core/pom.xml#L115-L208

**Comment by bpauli** [comment]
@edoardo-goracci The exclusion list in https://github.com/adobe/aem-core-email-components/blob/development/bundles/core/pom.xml#L169-L199 is to long. Please revisit. Thanks!

cc @stein-rockware

**Comment by stein-rockware** [comment]
com/adobe/cq/email/core/components/internal/services/CoreEmailAuthoringUIModeServiceImpl.class and
com/adobe/cq/email/core/components/internal/services/CoreEmailOpenCommand.class will be removed with https://github.com/adobe/aem-core-email-components/issues/141 anyway

**Comment by edoardo-goracci** [comment]
Hi @bpauli,
sure, I'll remove the exclusions. The models are already well tested, since codecov ignores this.
