### ISSUE TITLE
Maven project setup

### ISSUE THREAD

**Issue by ogebert** [adobe/aem-core-email-components#13]
A maven project similar to the [wcm-core-components](https://github.com/adobe/aem-core-wcm-components) needs to be created for our AEM artifacts.

Let's start with the following settings (for development):

```
    <parent>
        <groupId>com.adobe.cq</groupId>
        <artifactId>core.wcm.components.parent</artifactId>
        <version>2.17.15-SNAPSHOT</version>
        <relativePath>parent/pom.xml</relativePath>
    </parent>

    <artifactId>core.email.components.reactor</artifactId>
    <packaging>pom</packaging>
    <version>2.17.15-SNAPSHOT</version>

    <name>Adobe Experience Manager Core Email Components Reactor</name>

```

- [x] Copy existing structure from core components
- [x] Rename project
- [x] Update pom files
- [x] Remove stuff not needed in our context
- [x] Make sure initial build is working
- [x] Update readme.md with infos on the project & how to run a build

**Estimation: S (6 days)**

**Comment by VjekoSulentic** [comment]
Changes committed to the development branch.
Ready for code review @stein-rockware & @ogebert.
