### ISSUE TITLE
RTE Personalization Plugin broken after installing package 0.8.0

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#133]
Steps to reproduce: 
1. Create a new editable template after installing package 0.8.0. [Note: I verified that property acTemplateId was present on jcr:content for the template/page object)
2. Allow Text, Title (and any other components to the base container policy)
3. Enable template
4. Create a new page using the template
5. Open Page Properties. I observed the Network calls and I see an HTTP 400 (Bad Request) error with a message "Invalid recursion selector value 'metadata'" (please see screenshot below)
6. When I switch to Email tab, the RTE plugin is disabled for Email. 
7. Next, edit the page. Add a Text component
8. Edit the Text Component, Click on the Personalization RTE Plugin. It opens a pop-up, but there are no tokens.  (please see screenshot below). 

![image](https://user-images.githubusercontent.com/102314745/169883330-ae1398ad-5473-4f72-b85d-8b909e223064.png)

![image](https://user-images.githubusercontent.com/102314745/169883420-aaa5e60e-7bc4-4976-a934-bc8d52e17932.png)

**Comment by noorradi** [comment]
Hello @priyankpardiwala, 
Can you please confirm you have cq-mcm-campaign with the following version
![image](https://user-images.githubusercontent.com/61408904/170022118-6ccc9583-3ef3-4642-a641-d007ae19537e.png)
If not please update the version and let me know if the problem is resolved.
Kind Regards, 
Noor Radi

**Comment by priyankpardiwala** [comment]
Hi @noorradi , 

I have a more recent version 1.4.14. This version was shared by Sebastian back in March. Do you still want me to install the older version 1.3.26? 

![image](https://user-images.githubusercontent.com/102314745/170086057-6779c2b0-a03b-4b8f-a7c3-08798a889c3a.png)
