### ISSUE TITLE
Teaser Component - Image not added to the output html

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#134]
Steps to reproduce: 
1. Add a teaser component to the page.
2. Edit Teaser component. In the Assets tab, uncheck "Inherit featured image from page" checkbox.
3. Next, drag and drop an image from left pane.
4. provide alternative text for accessibility. 
5. Save the dialog. 

Expected output: 
Image shows up on the page

Actual Output: 
Image does not show on the page. No <img> tag in the markup when I inspected the component HTML. 

![image](https://user-images.githubusercontent.com/102314745/170088966-b223987d-f54c-4005-918b-0502fa305a5b.png)

![image](https://user-images.githubusercontent.com/102314745/170088993-643e941e-a4c6-4742-938d-4a5dc12d474e.png)

![image](https://user-images.githubusercontent.com/102314745/170089032-f560adcf-f5b0-4b2a-a10d-00f9a7a5fc5e.png)

![image](https://user-images.githubusercontent.com/102314745/170089073-1e2e8f74-e904-4150-950b-e63a3af4b078.png)

**Comment by noorradi** [comment]
Hello @priyankpardiwala, I followed the steps mentioned but I can't seem to reproduce the issue. 
Is this issue still present with the latest release? 
Thanks,
Noor
