### ISSUE TITLE
Teaser Component - Adding personalization token as a link incorrectly encodes the link

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#136]
I tested this with Teaser component but the issue likely exists on all the components that have Personalization RTE plugin enabled for Links. 

Essentially - I used a personalization token as the link (please see the screenshot below)

Actual Output: 
`<a class="cmp-teaser__title-link" href="%25=targetData.link%25" target="_blank">Test Title</a>`

Expected Output:
`<a class="cmp-teaser__title-link" href="<%=targetData.link%>" target="_blank">Test Title</a>`

![image](https://user-images.githubusercontent.com/102314745/170090837-770ef949-fe98-4400-a1e7-bcf8f98d0cdd.png)

**Comment by noorradi** [comment]
Hello @priyankpardiwala, the issue mentioned here is taken care of in #135
