### ISSUE TITLE
Approve for Campaign workflow does not work after installing package 0.8.0

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#138]
I created a new email page after installing package 0.8.0 and now when I try to run "Approve for Campaign" workflow, it does not approve the email. 

there is no apparent failure notifications on the screen but the workflow runs into a loop where it keeps asking me to "complete" a step. 

This was working fine until version 0.7.0 of the code package.

**Comment by stein-rockware** [comment]
@priyankpardiwala Does this issue still appear after installing the SP?

**Comment by priyankpardiwala** [comment]
This is working as expected after installing SP13. You can go ahead and close this one. Thank you.
