### ISSUE TITLE
Understand current campaign integration

### ISSUE THREAD

**Issue by stein-rockware** [adobe/aem-core-email-components#14]
- [x] Set up local ACC and AEM instances
- [x] Connect local ACC and AEM instances
- [x] Understand how the connection works, it's requirements and limitations
- [x] Check the source code of the AEM ACC connector
- [x] Document findings

**Estimation: S (6 days)**

**Open questions:**

- How can we access the source code of the AEM ACC connector? --> Check comments

**Comment by gabrielwalt** [comment]
https://git.corp.adobe.com/CQ/mcm
https://git.corp.adobe.com/CQ/integration-adobe-campaign
