### ISSUE TITLE
Button Component - adding Icon name does not show icon on the button

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#145]
Steps to reproduce: 
1. Add Button component to the page. 
2. Configure the icon name like shown in the screenshot below. 

![image](https://user-images.githubusercontent.com/102314745/171262457-29caff6f-29c8-4f4a-976f-e109ae176a7f.png)

![image](https://user-images.githubusercontent.com/102314745/171262512-a398454d-d1a5-454b-a095-9ff5ba8c828b.png)

Expected Behavior:
Icon shows up on the page

Actual Behavior: 
Icon does not show on the page.

**Comment by noorradi** [comment]
Hello @priyankpardiwala,
Please note that icon styling must be done in order for the icon to be displayed correctly.
Kindly find linked the read.me from the button core components on the icon styling 
https://github.com/adobe/aem-core-wcm-components/tree/main/content/src/content/jcr_root/apps/core/wcm/components/button/v2/button
Please confirm if this has fixed the issue.
Kind Regards, 
Noor Radi
