### ISSUE TITLE
Content Fragment Editor  - Personalization RTE Plugin does not work + Javascript errors

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#159]
I created a new Content Fragment using the standard content fragment template. 

Content Fragment editor loads with Javascript errors (please see screenshots below). Also - nothing appears when I click on the Personalization RTE Plugin. 

![image](https://user-images.githubusercontent.com/102314745/173984440-1a2bbd14-f0ee-4e51-b1df-378588cc515e.png)

**Comment by noorradi** [comment]
Hi @priyankpardiwala, 
We had a look into the issue you mentioned, could you kindly confirm if the folder properties has correct Adobe Campaign Configuration (Please see attached screenshot)
![Screenshot 2022-06-16 101739](https://user-images.githubusercontent.com/61408904/174025511-1ff11acc-250c-4999-8e17-30f40314a03a.png)
Thanks, 
Noor

**Comment by priyankpardiwala** [comment]
Hi @noorradi , 
My bad. I forgot to add Cloud Configuration to the folder. Now, the Personalization Plugin is working as expected, but I am seeing the Javascript errors for all content fragments.

**Comment by noorradi** [comment]
Hello @priyankpardiwala, 
Glad the RTE issue is fixed, as for the JS errors I can't seem to replicate those on the page.
![image](https://user-images.githubusercontent.com/61408904/174478060-3da00fd5-c334-43f7-b7d9-f20f92d3f797.png)
Please let me know if there is any component added to the page or any step I might be missing.
Kind Regards, 
Noor
