### ISSUE TITLE
Extend page resource types which can be used

### ISSUE THREAD

**Issue by stein-rockware** [adobe/aem-core-email-components#16]
Each email page is a page with the resource type of page provided within this repository of components. Customers could however create extensions of this page component which would potentially have a different resource type.

- [x] Check if ACC preview works
- [x] Document findings in Wiki so users / developers know how to set it up and what to do when creating their own page component

**Comment by noorradi** [comment]
The following [link](https://experienceleague.adobe.com/docs/experience-manager-65/administering/integration/campaignonpremise.html?lang=en#:~:text=checkbox%20is%20selected.-,Verifying%20the%20AEMResourceTypeFilter%20option,mcm/campaign/components/newsletter,-Configuring%20Adobe%20Experience) might be the answer to the question here, where the AEMResourceTypeFilter option is configured in Adobe Campaign.

**Comment by noorradi** [comment]
sling:resourceSuperType needs to be included into Adobe Campaign AEMResourceTypeFilter option to be able to retrieve page content from AEM on Adobe Campaign.
