### ISSUE TITLE
RTE Plugin with personalization fields

### ISSUE THREAD

**Issue by stein-rockware** [adobe/aem-core-email-components#17]
- RTE with capability to use the Campaign personalization fields
- Within the RTE, authors can pick Campaign variables, which will include a corresponding placeholder at the location of the cursor. This should be made available for the RTE of components, like the text component, but also for the RTE available for editing Content Fragments. Campaign will then replace these placeholders with the value of that variable when sending out the emails.

- [ ] Check existing implementation of the RTE Plugin and match to our requirements
- [ ] Check if changes in ACC are reflecting in AEM
- [ ] Check how to best integrate it into RTE and especially CF RTE, so we can use the existing RTE Plugin with the email core components

**Comment by noorradi** [comment]
There is already an RTE plugin available that can be used this is linked [here.](https://git.corp.adobe.com/CQ/mcm/blob/master/content/jcr_root/libs/mcm/campaign/components/touch-ui/clientlibs/rte/personalizationplugin/plugin.js)
Placeholders in this plugin are dynamically recovered from the Adobe Campaign nms:seedMember schema.

**Comment by VjekoSulentic** [comment]
To use the existing Personalization plugin, we enable it in dialog under the RTE field's rtePlugins node with
`<personalizationplugin
      jcr:primaryType="nt:unstructured"
      features="*"/>`
and then we add it to RTE field's uiSettings -> cui -> inline/dialogFullScreen to show in different edit modes.

https://experienceleague.adobe.com/docs/experience-manager-64/administering/operations/rich-text-editor.html?lang=en#understand-the-configuration-paths-and-locations
