### ISSUE TITLE
Style Inliner - Responsive CSS not working as expected on Outlook iPhone

### ISSUE THREAD

**Issue by dkadivendi** [adobe/aem-core-email-components#193]
We noticed that when an Email is sent through Adobe Campaign using the HTML source generated from the Style Inliner servlet as is, the contents of the Email are not responsive on Outlook iPhone.

Where as when the CSS from the Style Inliner source is well formatted (pretty-printed) using a CSS formatter the Email renders correctly on Mobile.

This issue is very specific to Outlook on iPhone, this is not an issue on Outlook Desktop App on Windows.

#### Sample Code that illustrates the problem from Style Inliner
`<style type="text/css">@media (max-width: 639px) {.root { width: 100% !important; }}@media (max-width: 639px) {.sample-email-root > center > table { width: 100% !important; }}.sample-email-root > center table span {font-family: Arial;}</style>`

### Not an issue when CSS is formatted as below
```
<style type="text/css">
 @media (max-width: 639px) {
     .root {
         width: 100% !important;
    }
}
 @media (max-width: 639px) {
     .sample-email-root > center > table {
         width: 100% !important;
    }
}
 .sample-email-root > center table span {
     font-family: Arial;
}
</style>
```

[Sample Code - Issue with Core Email Text Component.zip](https://github.com/adobe/aem-core-email-components/files/9242482/Sample.Code.-.Issue.with.Core.Email.Text.Component.zip)

**Comment by bpauli** [comment]
Might be related to some missing spaces in the CSS. 
See https://mymanycoloredways.com/posts/2021/02/fixing-media-queries-in-outlook-ios/

@dkadivendi Can you please also provide some example markup for this CSS so we do some testing with Litmus? Thanks!
