### ISSUE TITLE
Touchui not working properly

### ISSUE THREAD

**Issue by MalteHerberg** [adobe/aem-core-email-components#196]
Hi,

we are currently using the core components as a base for our email templates. 
### Expected Behaviour
All parsyses and touch UI functionalities should work

### Actual Behaviour
We've noticed now in the past versions already, that the touchUI is not loading properly. The divs of the parsys had 0 pixel, so selecting them was almost impossible. To fix that, we followed this tip here:
https://stackoverflow.com/questions/44637825/aem-6-2-drag-component-here-parsys-height-0px
And added this line:
   ` <sly data-sly-include='/libs/wcm/core/components/init/init.jsp' />`
to 
/apps/core/email/components/page/v1/page/head.html

in line 28 under the meta-tag blocks. This solved the issue for us, even though we had to keep updating the head.html with every. new version. 

Moving now to V0.11 of the core email components, the head.html is missing again the 
` <sly data-sly-include='/libs/wcm/core/components/init/init.jsp' />`
and the behaviour of the pages got worse. Now touchui is not loaded at all without this line of code. It just looks like this:
<img width="1745" alt="Screenshot 2022-08-04 at 08 03 17" src="https://user-images.githubusercontent.com/30293954/182780072-21eff4c6-7987-435b-8fcb-2cb89db03234.png">

After adding
` <sly data-sly-include='/libs/wcm/core/components/init/init.jsp' />`
it looks like this. 
<img width="1361" alt="Screenshot 2022-08-04 at 08 40 17" src="https://user-images.githubusercontent.com/30293954/182780350-fa5dd5dd-ebc3-4014-9493-230f9f2021a3.png">

 It's not possible to use the parsys that is shown on the screenshot, it's not selectable.
So does no one have the issue that we had before V0.11? That you had to add this line of code to make it work in general?
And then, does no one else have the issue that nothing works when moving to V0.11? 

#### Platform and Version
We are working on AEM 6.5.12. 

#### Logs taken while reproducing problem
There are some errors regarding a service user
`*ERROR* [172.20.0.1 [1659595849416] GET /content/campaigns/core-email-components-examples/master0/test/email-page-test.html HTTP/1.1] com.adobe.cq.wcm.core.components.internal.models.v1.ClientLibrariesImpl Cannot login as a service user
org.apache.sling.api.resource.LoginException: Cannot derive user name for bundle com.adobe.cq.core.wcm.components.core [625] and sub service components-service
`
See full log below.
[logs.txt](https://github.com/adobe/aem-core-email-components/files/9257360/logs.txt)

**Comment by Buuhuu** [comment]
The issue with loading the client libraries seems to be the cause of the missing styles in the editing interface. Before you make any changes to the head.html, make sure to resolve these issues.

Check if you deployed the `core.wcm.components.config` content package to you instance, in particular the service user mapping configuration:

https://github.com/adobe/aem-core-wcm-components/blob/main/config/src/content/jcr_root/apps/core/wcm/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-componentsservice.config

**Comment by MalteHerberg** [comment]
Hi Buuhuu,

so the general issue with V11 was more or less solved. What persists is the issue with the the necessity of including
`<sly data-sly-include='/libs/wcm/core/components/init/init.jsp' />`
which was there since we first started using the core components. The error with the clientlibraries seemed to be a good lead, but unfortunately after adding the config manually (it was deployed, but somehow not recognized. I checked under system/console/configMgr and the config was empty), the error does not show up in the log anymore. Still the parsys remains without height:
<img width="1990" alt="Screenshot 2022-08-05 at 11 40 21" src="https://user-images.githubusercontent.com/30293954/183050705-57f20349-f2b1-486c-b2e5-11eabc0c5e87.png">
Any followup ideas?

**Comment by Buuhuu** [comment]
The styles that give the paragraph system placeholders the necessary height come from the `cq.authoring.page` clientlib which is included by the [headlibs.html](https://github.com/adobe/aem-core-wcm-components/blob/main/content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/headlibs.html#L20) template in the [page v1](https://github.com/adobe/aem-core-email-components/blob/development/content/src/content/jcr_root/apps/core/email/components/page/v1/page/head.html#L36). Including the old init.jsp is not necessary. 

I have seen a similar issue in the past when switching between classic and touchui. Can you remove all your cookies and try to open the editor again?

**Comment by MalteHerberg** [comment]
Hi Buuhuu. I have to revert on my statement before, the other problem unfortunately is not solve, so I actually have go back to my initial post. 

Issue 1. Bevor V0.11 the TouchUI only works with 
`<sly data-sly-include='/libs/wcm/core/components/init/init.jsp' />`
in the head.html. You suggestions to delete the cookies does not work. I tried it with two different local AEM systems in incognito mode. This issues persists across all our local AEM systems in our team including the test environments in the cloud.

Issue 2. After V0.11 touchui is completely broken and does not render at all. Instead classic UI somehow trys to render underneath. 
<img width="1361" alt="182780350-fa5dd5dd-ebc3-4014-9493-230f9f2021a3" src="https://user-images.githubusercontent.com/30293954/183892197-5c8e9290-c570-40df-a3c3-d22b466438d6.png">

Before my second post in this threat I found out, that the 2. issue only occurs if the content is under 
`/content/campaigns`
If it's in the regular content tree under
`/content/core-email-components-examples/`
it looks almost fine, but works as intended. 
![Screenshot 2022-08-10 at 13 41 29](https://user-images.githubusercontent.com/30293954/183892585-156bb46e-9234-4734-b67d-85124eccd18d.png)
When I rename the _/content/campaigns_ folder to any other name that does NOT include _campaigns_, e.g. _/content/email_, everything works again. This issue persist on both the example pages from core email components as well as our own content tree within the campaigns node, which is currently a huge problem for us. 
I thought this might be a problem of our own AEM environment due to some customisation, but I've not tested it on a different AEM environment which doesn't have those changes and it also happens.

Issue 1. always happens, no matter if it's in /content/campaigns or any other re-named content tree.

Anyone having the same issue ?

**Comment by Buuhuu** [comment]
After an offline analysis we found the following:

- With 6.5 SP13 and earlier the Core E-Mail Components Page is not properly opened with TouchUI, but requires that. Official support is with SP14+
- The `cq.authoring.page` was not loaded properly, because the [ACS Commons I18nInjector](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/acs-aem-commons-4.1.0/bundle/src/main/java/com/adobe/acs/commons/models/injectors/impl/I18nInjector.java) interfered with the ClientLibraries model which implicitly uses [the BindingsInjector to inject the categories](https://github.com/adobe/aem-core-wcm-components/blob/core.wcm.components.reactor-2.19.2/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java#L93-L95). Due to that the `categories` were not available in the model and hence not included in the page.
