### ISSUE TITLE
Build Failure - StylesInlinerServiceImplTest Test Case Failing

### ISSUE THREAD

**Issue by sachin-arora** [adobe/aem-core-email-components#204]
### Expected Behaviour
Build should be Successful
### Actual Behaviour
Build is failing as few Junit Tests are failing
### Reproduce Scenario (including but not limited to)
Checkout development branch and run following maven command : mvn clean install -Pcloud -PautoInstallPackage
#### Steps to Reproduce
Mentioned Above
#### Platform and Version
AEMaaCS - 2022.7.8085.20220725T140323Z-220700
#### Logs taken while reproducing problem
[ERROR] Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.597 s <<< FAILURE! - in com.adobe.cq.email.core.components.internal.services.StylesInlinerServiceImplTest
[ERROR] success  Time elapsed: 0.424 s  <<< FAILURE!
org.opentest4j.AssertionFailedError:
expected: <p::before, p::after { content: '"'; }
@media screen and (max-width: 640px) { table.layout { width: 100% !important; } }
@media screen and (max-width: 480px) { td.layout-column { display: block !important; width: 100% !important; } }
.ExternalClass { width: 100%; }
h4 { font-weight: bold; }> but was: <p::before, p::after { content: '"'; }
@media screen and (max-width: 640px) { table.layout { width: 100% !important; } }
@media screen and (max-width: 480px) { td.layout-column { display: block !important; width: 100% !important; } }
.ExternalClass { width: 100%; }
h4 { font-weight: bold; }>
        at com.adobe.cq.email.core.components.internal.services.StylesInlinerServiceImplTest.success(StylesInlinerServiceImplTest.java:78)

**Comment by bpauli** [comment]
This issue was fixed meanwhile.
