### ISSUE TITLE
Build Failure - Antrun plugin failing

### ISSUE THREAD

**Issue by sachin-arora** [adobe/aem-core-email-components#205]
### Expected Behaviour
Build should be Successful
### Actual Behaviour
Build is failing due to maven-antrun-plugin failure.
### Reproduce Scenario (including but not limited to)
Checkout development branch and run following maven command : mvn clean install -Pcloud -PautoInstallPackage -Dmaven.test.skip=true
Skipping Test execution due to other issue #204 

I removed maven-antrun-plugin from content/pom.xml to avoid below error. After deployment I see email components are getting deployed in /apps/core/email instead of /libs/core/email. Also strange thing is, Core components get removed i.e. /libs/core/wcm/components does not exist after package deployment. Please advise if its because of antrun plugin removal.

#### Steps to Reproduce
Mentioned Above
#### Platform and Version
AEMaaCS - 2022.7.8085.20220725T140323Z-220700
#### Logs taken while reproducing problem

[INFO] Adobe Experience Manager Core Email Components Content Package FAILURE [ 12.343 s]

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.3:run (default) on project core.email.components.content: An Ant BuildException has occured: Replace: source file DIRECTORY_PATH\aem-core-email-components\content\target\jcr_root\libs\core\wcm\components\breadcrumb\v2\breadcrumb\.content.xml doesn't exist -> [Help 1]

**Comment by Buuhuu** [comment]
Thanks for reporting this. 

Currently the Core E-Mail Components are not part of the AEM as a Cloud Service product. They are not included the way the Core WCM Components are. However, the Core WCM Components acted as boilerplate for this project and so there is the `-Pcloud` build profile. Long term we should and want to fix this, see the PR #200. 

For project development it should be fine to just install the Core E-Mail Components in /apps without the `-Pcloud` profile
