### ISSUE TITLE
Segmentation Component - Custom Conditions are stored under root (/)

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#209]
Segmentation component stores custom segments/conditions at the root level. Please see the screenshot below. 

![image](https://user-images.githubusercontent.com/102314745/188207026-047ff889-8165-436a-9d61-6363c1f0ef93.png)

This is leading to another error (please see below) when an author who does not have write access at root level tries to add/edit the segmentation component. 

![image](https://user-images.githubusercontent.com/102314745/188206887-6de63e59-7bca-459f-b5b3-e493bb0ac150.png)

I did not notice this earlier because I kept testing the component with admin account. But I still don't understand why conditions entered at the component level are getting stored at root level as opposed to component properties.

**Comment by bpauli** [comment]
Internal reference SITES-7909
