### ISSUE TITLE
Segmentation Component - Ability to Clone a Segment when adding more segmented content to a page

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#210]
Can segmentation component have a similar capability as native Targeting where the contents of a segment (say default segment) gets copied over every time author adds a new segment? 

With the current Segmentation component (based on Tabs component), when we add segments, it adds a new tab with a component of our choice but there is no option to clone the contents of a previously added tab. This means that - even though author wants to do minor tweaks to the content based on the Segment, they have to re-author all the components. 

It would be really beneficial for the authors if Segmentation Component can be extended to provide this capability.

**Comment by bpauli** [comment]
Internal reference SITES-7909

**Comment by bpauli** [comment]
Maybe one option would be to enhance the childreneditor for panels with a cop'n paste option. TBD with product management.  https://xd.adobe.com/view/20df175b-e251-430b-aaf2-5c06a9fb5ad1-758c/

@gabrielwalt

**Comment by bpauli** [comment]
The PR in #233 will add a new clone button to the Segment Editor

<img width="688" alt="image" src="https://user-images.githubusercontent.com/689884/194544813-b93457b8-7291-4c30-be6b-103a49c6440e.png">
