### ISSUE TITLE
Style Inliner - Gmail App Issue

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#211]
While building our components as per our brand guidelines we came across a strange (& annoying) issue with Gmail App. Apparently - Gmail App only allows <style> blocks with a maximum size of 16Kb. If the contents of the <style> tag exceed 16Kb, Gmail App simply removes the entire <style> tab from the final output. 

Current version of Style Inliner, creates only one <style> tag with all the CSS as per the CSS defined in the clientlib. Unfortunately - 16Kb is not a lot and it fills up really quickly and breaks responsiveness in our email. 

This is a critical issue as the emails just don't render as expected in Gmail App. Can we meet to discuss a possible fix for this. We have some ideas but wanted to have a broader discussion with the team on what could be a fool-proof solution to this problem.

**Comment by bpauli** [comment]
Internal reference SITES-7908
