### ISSUE TITLE
Segmentation Component - Unexpected Behavior in Dialog when deleting a segment

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#223]
Steps to reproduce:
1. Add segmentation component to the page
2. Add 2 or 3 segments 
3. Author content within each segment
4. Open dialog for Segmentation component
5. Delete any of the segments that you added previously
6. Notice that the dialog shows the actual content of another segment in it.

Please see the screenshot below for a visual. 
![image](https://user-images.githubusercontent.com/102314745/192622675-b632105e-fd66-4187-a3f4-0ab81585f356.png)

Closing and reopening the dialog does resolve the issue, but wanted to report this as an issue.

**Comment by bpauli** [comment]
This issue will be fixed with the upcoming wcm core components version. Which contains the changes of the PR https://github.com/adobe/aem-core-wcm-components/pull/2302

**Comment by Buuhuu** [comment]
The Dialog also breaks when 

- add 3 segments to the Segmentation Component, do not save
- deleting them without saving the dialog

Actual Behaviour:

The dialog panel reloads and some of the unsaved changes get lost

Expected Behaviour:

The unsaved changes are preserved.

**Comment by Buuhuu** [comment]
duplicates https://github.com/adobe/aem-core-wcm-components/issues/2314

**Comment by bpauli** [comment]
Will be fixed with https://github.com/adobe/aem-core-email-components/issues/210
