### ISSUE TITLE
Segmentation Component - Issues when switching from custom to default segment

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#243]
Steps to reproduce
1. Add segmentation component
2. Add 2 segments. Both custom. 
3. Submit the dialog. As expected, we see 2 tabs corresponding to 2 custom segments. 
4. Re-edit the component and switch the 2nd custom segment to Default. 
5. As expected, the custom fields are hidden. 
6. Submit the dialog. Notice that tab title does not show default. Instead, it still custom condition. 
7. Re-edit the dialog, switch that default segment back to Custom. Update the segment name and condition. 
8. Submit the dialog and notice that component output and the view as published output. In our test, it did not save the new segment information. 

Please let me know if you would like me to demo this. 

Thank you.

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES as Bug
