### ISSUE TITLE
Page component

### ISSUE THREAD

**Issue by stein-rockware** [adobe/aem-core-email-components#3]
Based on the Core Page component v3

Provide the following edit dialog options:
* Main tab
  - Email subject (`jcr:title`)
  - Description (`jcr:description`, text area)
  - Language + language root
  - Tags
  - HTML ID
  - Template settings
* Images
  - Page image
  - Thumbnail
* Cloud configuration
* Permissions
* Remove any page properties not mentioned here

Provides the following "Email Header" component that is included by the page template as a mandatory but editable component:
* Subject
   - RTE with only the Campaign personalization options enabled (no capability to create for e.g. bold text)
   - The value defaulting to the `jcr:title` defined on the page
* Pre-header
   - RTE with the Campaign personalization fields (no capability to create for e.g. bold text)
   - The value defaulting to the `jcr:description` defined on the page

Provides the following page policy (aka design dialog) options:
* Main tab
  - Client libraries
* Styles tab

Requirements:
* Extends the base or core page component.
* Functions with Editable Templates.
* Inlines all CSS into the HTML output on a STYLE element that is then further inlined as STYLE attributes on the individual elements by the CSS inliner rewriter.
* Includes no JS from any of the included clientlibs.
* Pre-header adds the entered content at the top of the page body as follows:<br>`<span style="display: none; …">${page.preheader}</span>`
* Within the template editor, authors can configure an email header and/or footer that would be shared among all email pages resulting from this page template. In the template editor, authors can also pre-configure the design configuration of the components, like their style system.
* Provides the following "Email Header" component that is included by the page template as a mandatory but editable component.

- [x] Create template
- [x] Create page component
- [x] Update page dialog
- [x] Provide page policies
- [x] Integrate CSS inliner
- [x] Exclude / Remove JS from result -> [Technical documentation](https://github.com/adobe/aem-core-email-components/wiki/HTML-sanitizing:-Technical-documentation)
- [x] Include RTE Plugin with personalization fields
- [x] Include Header / Footer
- [x] Include Email Header component

Estimation: M (10 days)

**Comment by VjekoSulentic** [comment]
Added a "Test component" to showcase the CSS inliner.
The servlet for inlining the page has a selector "inline-styles".
