### ISSUE TITLE
Remove Layouting options from page & components

### ISSUE THREAD

**Issue by stein-rockware** [adobe/aem-core-email-components#47]
Removing the arrow icons from the component menu as well as Layout mode to remove redundancies since you have since incorporated this as part of the Container component dialog for column layout.

**Comment by gabrielwalt** [comment]
This can probably be achieved by removing all `cq:responsive` nodes:
- On the template: https://github.com/adobe/aem-project-archetype/blob/develop/src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/page-content/structure/.content.xml#L51-L62
- On the content: https://github.com/adobe/aem-project-archetype/blob/develop/src/main/archetype/ui.content/src/main/content/jcr_root/content/__appId__/language-masters/en/.content.xml#L52-L57
