### ISSUE TITLE
Style Inliner inlines the generic styles instead of specific one.

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#63]
I have a CSS file that looks something like this

```
p{
color: red;
}

.cmp-text--regular p{
font-size: 20px; 
color: darkgrey; 
}
```

### Expected Behaviour
The expected behavior for the CSS inliner would be to create style attribute
```
<div class="cmp-text--regular">
<p style="font-size:20px; color: darkgrey;">This should be dark grey</p>
</div>
```

### Actual Behaviour
```
<div class="cmp-text--regular">
<p style="font-size:20px; color: red;">This should be dark grey</p>
</div>
```

Notice that the font color is red instead of darkgrey.

**Comment by edoardo-goracci** [comment]
Hello Priyank,
Thank you for your test. I confirm that it is a bug, I am going to fix it.

**Comment by edoardo-goracci** [comment]
PR created:

https://github.com/adobe/aem-core-email-components/pull/74
