### ISSUE TITLE
Container Component - Not able to edit any child components

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#68]
Not able to edit Text (or any component) to container component. 

Steps to reproduce.
1. Create an editable template
2. Set policy for Root layout container. Allow Email Core Container component in the policy. 
3. While in "Structure", add "Container" component. 
4. Set a policy for the Container component. Allow Text, Image, Segmentation component etc to the policy
5. Unlock Container component
6. Switch to "Initial Content" mode in the template. You should be able to see the Container component. 
7. Click "+" button, add "Text" component
8. Notice that - when you click on the text component, it does not load the toolbar at all, preventing us from editing the component.

**Comment by noorradi** [comment]
Hello @priyankpardiwala, 
I followed the steps listed above and was able to successfully edit the text component. 
![image](https://user-images.githubusercontent.com/61408904/160278403-31bfc925-7ccb-4b39-908f-f019ea7c0775.png)
Please let me know if I missed anything in your steps. 
Kind Regards,
Noor
