### ISSUE TITLE
Container Component - loads with 0px width

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#69]
It looks like the container component does not load the corresponding clientlib when we add the component in the Editable template/page. 

I was able to get around it by manually adding the clientlib in the Page Policy for Editable template, but I feel it would be best if the clientlib gets loaded automatically when the page loads without needing template author to add it manually.

**Comment by noorradi** [comment]
Hello @priyankpardiwala,
The issue mentioned has been fixed and will be included with the next package drop.
Kind Regards, 
Noor
