### ISSUE TITLE
Page Component - Question on using Allowed Template

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#70]
The current version Email Page component has a metadata property that allows us to specify "Allowed Templates".  I know that the WCM Page component also has a field that allows you to specify the /conf folder to associate the allowed Editable templates. 

Is there a plan to add that option to the Email Page component? or should we continue to use "Allowed Templates" fields to associates editable templates.

**Comment by stein-rockware** [comment]
For now, we will make use of "Allowed Templates" within the Email Core Components
