### ISSUE TITLE
Question: Root Container component

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#77]
Since the Email Page component is proxied from the Web Page component, it uses the "Layout Container" component from Web Core components as the "Root" container. 

Are we planning to update this so that instead of using Web component, the Email Page will use the email container component as the "Root" container?

**Comment by stein-rockware** [comment]
We will switch the Layout Container to Email Container Component with story https://github.com/adobe/aem-core-email-components/issues/90
