### ISSUE TITLE
Personalization RTE Plugin is Disabled in Page Properties for authoring Email Subject and Preheader

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#92]
Steps to replicate - 
1. Install email core package 0.5.0
2. Create a new editable template using the page component provided in the above package. 
3. Enable the template
4. Create a new page using the new template. 
5. Edit the "Page Properties", go to "Email" tab. 
6. RTE plugin for Personalization is disabled for Email Subject and Preheader fields.

**Comment by stein-rockware** [comment]
Hi @priyankpardiwala ,
I've checked the issue on your instance. It looks like something is wrong with Contexthub configuration on the instance. After copying /libs/settings/cloudsettings/legacy/contexthub-adobecampaign to /etc/cloudsettings/default/contexthub-adobecampaign, personalization now works on the page properties as well.
I'm not sure why it is not using the configuration on /libs/settings/cloudsettings/legacy/contexthub-adobecampaign is not used. Maybe there was an issue with a previous service pack installation...

**Comment by priyankpardiwala** [comment]
Hi @stein-rockware  - I am able to reproduce this issue after installing package 0.6.0. Can we re-open this?
