### ISSUE TITLE
Personalization Plugin is does not work for Text component

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#93]
Steps to reproduce
1. Create and Enable Editable template
2. Allow text component on layout container
3. Create a new page using the template
4. Add a Text component
5. Use RTE plugin for Personalization
6. Expected Behavior is to be able to select personalization elements but no popup for selecting personalization blocks shows up.

**Comment by stein-rockware** [comment]
Issue was due to an error while installing the package. It's resolved now.

**Comment by priyankpardiwala** [comment]
I am able to reproduce the issue after installing package 0.6.0 in our environment. @stein-rockware - can we reopen this one?
